_base_: ast2_ucf101.yaml
data:
  cache_enabled: true
  cache_dir: outputs/cache/ucf101
train:
  epochs: 1
  out_dir: outputs/SMOKE/ast2_ucf101

training:
  val_max_batches: 200
  val_log_interval: 50
  val_every_epochs: 1
