_base_: ../vc_phase3_full_ucf101.yaml

training:
  inner_steps_layout: 1
layout:
  optimize_layout: true
layout_seed:
  method: traffic_aware
  enable_micro_place: true
  micro_place_steps: 80
  micro_place_T0: 1.0
  micro_place_alpha: 0.995
